name: Run Script

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run script
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          API_KEY: ${{ secrets.API_KEY }}
        run: node script.js
